sudo: false

language: scala
scala:
  - 2.13.5
  - 3.0.0-RC2

dist: xenial
services:
  - xvfb

jdk:
  - openjdk11
  - openjdk15

install:
  - |
    # update this only when sbt-the-bash-script needs to be updated
    export SBT_LAUNCHER=1.5.0
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt

script:
  - java -version
  - sbt ++$TRAVIS_SCALA_VERSION test

